class Constants:
    USER_TASK_RUNNING=1
    USER_TASK_FAILED=2
    USER_TASK_SUCCESS=3
    USN_DATA_PRESENT=1
    USN_DATA_FAILED=2
    USN_DATA_ABSENT=3
    TASK_DATA_EXISTS=0
    TASK_STARTED=2
    TASK_DATA_FAILED=1